
- hosts: all
  gather_facts: yes  
  vars:
    pod_network_cidr: "10.142.0.0/24"
    ignore_preflight: "--ignore-preflight-errors=NumCPU,Mem"
    ubuntu_home: "/home/ubuntu"
    cni_yaml_url: "https://projectcalico.docs.tigera.io/manifests/calico.yaml"
    cni_yaml: "calico.yaml"

- hosts: controller
  gather_facts: yes
  tasks:

  - name: kubeadm reset existing cluster
    become: yes
    shell: kubeadm reset --force

  - name: delete cni configuration in /etc/cni/net.d
    become: yes
    file:
      state: absent
      path: /etc/cni/net.d
  
  - name: delete kube config dir
    file:
      state: absent
      path: "{{ ubuntu_home }}/.kube"

  - name: kubeamd init
    become: yes
    shell: kubeadm init --upload-certs --pod-network-cidr "{{ pod_network_cidr }}" {{ ignore_preflight }}

  - name: create .kube directory for ubuntu user
    file:
      path: "{{ ubuntu_home }}/.kube"
      state: directory

  - name: copy admin.conf to .kube directory for ubuntu user
    become: yes
    copy:
      src: /etc/kubernetes/admin.conf
      remote_src: yes
      dest: "{{ ubuntu_home }}/.kube/config"
      owner: ubuntu
      group: ubuntu

  - name: create new join token and get command
    shell: "kubeadm token create --print-join-command"
    register: kubeadm_token_create

  - set_fact:
      kubeadm_join_cmd: "{{ kubeadm_token_create.stdout }}"  
 
  - name: get calico cni yaml
    get_url:
      url: "{{ cni_yaml_url }}"
      dest: "{{ ubuntu_home }}/{{ cni_yaml }}"
  
  - name: deploy calico cni
    shell: kubectl apply -f {{ cni_yaml }}

  - name: sleep for 30 seconds
    wait_for:
      timeout: 30
    delegate_to: localhost

  - name: view nodes (STATUS should be Ready)
    shell: kubectl get nodes


- hosts: worker
  gather_facts: yes  
  tasks:

  - name: kubeadm reset existing cluster
    become: yes
    shell: kubeadm reset --force

  - name: delete cni configuration in /etc/cni/net.d
    become: yes
    file:
      state: absent
      path: /etc/cni/net.d
  
  - name: delete kube config dir
    file:
      state: absent
      path: "{{ ubuntu_home }}/.kube"

  - name: join cluster
    shell: sudo {{ hostvars['controller'].kubeadm_join_cmd }} {{ ignore_preflight }}

  - name: sleep for 30 seconds
    wait_for:
      timeout: 30
    delegate_to: localhost


- hosts: controller
  gather_facts: yes  
  tasks:
  
  - name: view nodes (There should be 2 nodes)
    shell: kubectl get nodes

