
- hosts: controller
  gather_facts: yes  
  tasks:

  - name: kubeadm reset existing cluster
    become: yes
    shell: kubeadm reset --force

  - name: delete cni configuration in /etc/cni/net.d
    file:
      state: absent
      path: /etc/cni/net.d

  - name: kubeamd init
    become: yes
    shell: kubeadm init --upload-certs --pod-network-cidr "10.142.0.0/24" --ignore-preflight-errors=NumCPU,Mem

  - name: create .kube directory for ubuntu user
    file:
      path: $HOME/.kube
      state: directory

  - name: Copy file with owner and permissions
    become: yes
    copy:
      src: /etc/kubernetes/admin.conf
      remote_src: yes
      dest: /home/ubuntu/.kube/config
      owner: ubuntu
      group: ubuntu

  # - name: set kubeconfig for ubuntu user
  #   shell: | 
  #     mkdir -p $HOME/.kube
  #     sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
  #     sudo chown $(id -u):$(id -g) $HOME/.kube/config

  # - name: set kubeconfig for root user
  #   become: yes
  #   shell: | 
  #     mkdir -p /home/root/.kube
  #     sudo cp -i /etc/kubernetes/admin.conf /home/root/.kube/config
  #     sudo chown $(id -u):$(id -g) /home/root/.kube/.kube/config
  
  - name: get calico cni yaml
    get_url:
      url: https://projectcalico.docs.tigera.io/manifests/calico.yaml
      dest: /$HOME/calico.yaml
  
  - name: deploy calico cni
    shell: kubectl apply -f calico.yaml

  - name: sleep for 30 seconds
    wait_for:
      timeout: 30
    delegate_to: localhost

  - name: view nodes (STATUS should be Ready)
    shell: kubectl get nodes