
- hosts: controller
  gather_facts: yes  
  tasks:

  - name: kubeadm reset existing cluster
    become: yes
    shell: kubeadm reset --force

  - name: delete cni configuration in /etc/cni/net.d
    file:
      state: absent
      path: /etc/cni/net.d
  
  - name: delete kube config dir
    file:
      state: absent
      path: $HOME/.kube

  - name: kubeamd init
    become: yes
    shell: kubeadm init --upload-certs --pod-network-cidr "10.142.0.0/24" --ignore-preflight-errors=NumCPU,Mem

  - name: create .kube directory for ubuntu user
    file:
      path: $HOME/.kube
      state: directory

  - name: copy admin.conf to .kube directory for ubuntu user
    become: yes
    copy:
      src: /etc/kubernetes/admin.conf
      remote_src: yes
      dest: /home/ubuntu/.kube/config
      owner: ubuntu
      group: ubuntu
  
  - name: get calico cni yaml
    get_url:
      url: https://projectcalico.docs.tigera.io/manifests/calico.yaml
      dest: /$HOME/calico.yaml
  
  - name: deploy calico cni
    shell: kubectl apply -f calico.yaml

  - name: sleep for 30 seconds
    wait_for:
      timeout: 30
    delegate_to: localhost

  - name: view nodes (STATUS should be Ready)
    shell: kubectl get nodes


- hosts: worker
  gather_facts: yes  
  tasks:

  - name: kubeadm reset existing cluster
    become: yes
    shell: kubeadm reset --force

  - name: delete cni configuration in /etc/cni/net.d
    file:
      state: absent
      path: /etc/cni/net.d
  
  - name: delete kube config dir
    file:
      state: absent
      path: $HOME/.kube

  