---
- name: kubernetes-packages-install
  hosts: all 

  tasks: 

  # - name: packages | ensure apt list dir exists
  #   file:
  #     path: /var/lib/apt/lists/
  #     state: directory
  #     mode: 0755

  # - name: update apt list
  #   become: yes
  #   apt:
  #     update_cache: yes    

  - name: install docker required packages
    become: yes
    apt:
      name: "{{item}}"
      state: latest
      update_cache: yes 
    loop:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
  
  - name: add docker official gpg key
    become: yes
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Set the stable docker repository
    apt_repository: 
      repo: "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      state: present
      update_cache: yes 

  - name: install docker
    become: yes
    apt:
      name: "{{item}}"
      update_cache: yes 
    loop:
      - docker-ce=20.10.12
      - docker-ce-cli=20.10.12
      - containerd.io=20.10.12
  
  - name: set cgroup to systemd for docker
    copy:
      dest: "/etc/docker/daemon.json"
      content: |
        {
          "exec-opts": ["native.cgroupdriver=systemd"]
        }
  
  - name: let iptable see bridged traffic
    shell: sudo sysctl --system

  

