---
- name: kubernetes-packages-install
  hosts: all 

  tasks: 

  - tasks:
  - name: update apt list
    apt:
      update_cache: yes

  - name: install docker required packages
    apt:
      name: "{{item}}"
      state: latest
    loop:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
  
  - name: add docker official gpg key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present


  - name: install docker
    apt:
      name: "{{item}}"
      state: latest
    loop:
      - docker-ce=20.10.12
      - docker-ce-cli=20.10.12
      - containerd.io=20.10.12
  
  - name: set cgroup to systemd for docker
    copy:
      dest: "/etc/docker/daemon.json"
      content: |
        {
          "exec-opts": ["native.cgroupdriver=systemd"]
        }
  
  - name: let iptable see bridged traffic
    shell: sudo sysctl --system

  

