---
- name: multipass-clean-vms
  hosts: all 

  tasks: 

  - name: multipass list (before)
    win_shell: multipass list

  - name: multipass clean 
    win_shell: |
      multipass delete controller worker
      multipass purge
  
  - name: multipass list (after)
    win_shell: multipass list

