---
- name: multipass-provision-vms
  hosts: all 

  tasks: 

  - name: multipass list (before)
    win_shell: multipass list

  - name: multipass clean 
    win_shell: |
      multipass delete controller worker
      multipass purge

  - name: multipass start controller
    win_shell: multipass launch --disk 5G --mem 512M --cpus 1 --name controller

  - name: multipass start controller
    win_shell: multipass launch --disk 5G --mem 512M --cpus 1 --name worker

  - name: multipass list (after)
    win_shell: multipass list

  - name: Create a directory if it does not exist
    win_shell: |
      $FolderName = "~/tmp"
      if (Test-Path $FolderName) {   
        Write-Host "Folder Exists"
        # Perform Delete file from folder operation
      }else{  
        #PowerShell Create directory if not exists
        New-Item $FolderName -ItemType Directory
        Write-Host "Folder Created successfully"
      }

  - name: copy network netplan for controller
    ansible.builtin.copy:
      src: 01-controller-network.yaml
      dest: ./tmp/01-controller-network.yaml

  - name: copy network netplan for worker
    ansible.builtin.copy:
      src: 01-worker-network.yaml
      dest: ./tmp/01-worker-network.yaml

