---
- name: multipass-provision-vms
  hosts: all 

  tasks: 

  - name: multipass list (before)
    win_shell: multipass list

  - name: multipass clean 
    win_shell: |
      multipass delete controller
      multipass delete worker
      multipass purge

  - name: multipass start controller
    win_shell: multipass launch --disk 5G --mem 512M --cpus 1 --name controller

  - name: multipass start worker
    win_shell: multipass launch --disk 5G --mem 512M --cpus 1 --name worker

  - name: multipass list (after)
    win_shell: multipass list

  - name: Create a directory if it does not exist
    win_shell: |
      $FolderName = "./multipass-provision-vms"
      if (Test-Path $FolderName) {   
        Write-Host "Folder Exists"
        Remove-Item $FolderName -Recurse
      }
      New-Item $FolderName -ItemType Directory
      Write-Host "Folder Created successfully"      

  - name: copy network netplan for controller
    ansible.builtin.copy:
      src: 01-controller-network.yaml
      dest: ./multipass-provision-vms/01-controller-network.yaml

  - name: copy network netplan for worker
    ansible.builtin.copy:
      src: 01-worker-network.yaml
      dest: ./multipass-provision-vms/01-worker-network.yaml
  
  - name: move network netplan to VMs and copy to /etc/netplan/
    win_shell: |
      multipass transfer ./multipass-provision-vms/01-controller-network.yaml controller:01-controller-network.yaml
      multipass transfer ./multipass-provision-vms/01-worker-network.yaml worker:01-worker-network.yaml
      multipass exec controller -- sudo cp 01-controller-network.yaml /etc/netplan/ 
      multipass exec worker -- sudo cp 01-worker-network.yaml /etc/netplan/ 
  
  - name: restart VMs to apply netplan changes
    win_shell: |
      multipass restart controller worker

